"use client";

/* eslint-disable @typescript-eslint/no-misused-promises */
import * as z from 'zod';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XChuqWMY264
 */
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "src/components/ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import type { OnboardingState, RouterSchema } from '@/app/enroll/page';
import { useEffect, useState } from 'react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { useToast } from '@/components/ui/use-toast';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { createClient } from '@/utils/supabase/client';
import { type StudioSchema } from 'lib/db-types';

const formSchema = z.object({
    first_name: z.string().trim().min(1).max(50),
    last_name: z.string().trim().min(1).max(50),
    email: z.string().trim().email(),
    studioCode: z.string().trim().min(5).max(5)
});

export type FormSchema = z.infer<typeof formSchema>;

type Props = {
    query: RouterSchema | undefined,
    setFormData: (data: FormSchema) => void,
    setState: (state: OnboardingState) => void,
    setStudio: (studio: StudioSchema) => void,
    studio: StudioSchema | null
}

export function Enrollment(props: Props) {
  const sb = createClient();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const code = props.query ? props.query.code : "";

  const form = useForm<FormSchema>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      first_name: "",
      last_name: "",
      email: "",
      studioCode: code ?? "", // Initialize with code from query params
    },
  });

  useEffect(() => {
    if (code) {
      form.setValue("studioCode", code);
    }
  }, [code, form]);

  const onSubmit = async (data: FormSchema) => {
    setLoading(true);
    props.setFormData(data);
    
    try {
      const codeRes = await sb.from("studios").select("*").eq("code", data.studioCode);
      console.log(codeRes);
      
      if (codeRes.error) {
        toast({
          variant: "destructive",
          title: "Database error",
          description: "Unable to verify studio code. Please try again."
        });
        console.log(codeRes.error);
        setLoading(false);
        return;
      }
      
      const resdata = codeRes.data;
      if (resdata.length === 0) {
        toast({
          variant: "destructive",
          title: "Invalid studio code",
          description: "No studio found with that code. Please check and try again."
        });
        setLoading(false);
        return;
      }

      // Success! Studio found
      toast({
        title: "Studio found!",
        description: `Enrolling in ${(resdata[0] as StudioSchema).studio_name}...`
      });
      
      props.setState("schedule");
      props.setStudio(resdata[0] as StudioSchema);
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Unexpected error",
        description: "Something went wrong. Please try again."
      });
      console.error(error);
    } finally {
      setLoading(false);
    }
  };
  // Check if the studio is a chamber music group (once loaded)
  const isChamberMode = props.studio?.studio_mode === 'chamber_music';

  return (
    <div className="flex justify-center items-center min-h-screen bg-landing-background font-arimo">
      <Card className="w-full max-w-md mx-auto bg-white border border-landing-blue/20">
        <CardHeader>
          <CardTitle className="text-center text-landing-blue">
            {isChamberMode ? "Join a Chamber Group" : "Enroll in a Studio"}
          </CardTitle>
          <CardDescription className="text-center text-landing-blue/70">
            {isChamberMode
              ? "Enter your name, email and group code to join."
              : "Enter your name, email and studio code to enroll."
            }
          </CardDescription>
        </CardHeader>
        <CardContent className="">
          <Form {...form}>
            <form className="space-y-4" onSubmit={form.handleSubmit(onSubmit)}>
              <FormField
                control={form.control}
                name="first_name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-landing-blue font-medium">First Name</FormLabel>
                    <FormControl>
                      <Input placeholder="First" disabled={loading} {...field} className="border-landing-blue/20 focus:border-landing-blue" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
              control={form.control}
              name="last_name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="text-landing-blue font-medium">Last Name</FormLabel>
                  <FormControl>
                    <Input placeholder="Last" disabled={loading} {...field} className="border-landing-blue/20 focus:border-landing-blue" />
                  </FormControl>
                  <FormDescription className="text-landing-blue/60">
                    Your full name as you would like it to appear to the {isChamberMode ? "group" : "studio"}.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
              />
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-landing-blue font-medium">Email</FormLabel>
                    <FormControl>
                      <Input placeholder="name@gmail.com" disabled={loading} {...field} className="border-landing-blue/20 focus:border-landing-blue" />
                    </FormControl>
                    <FormDescription className="text-landing-blue/60">
                      Your email to save for future communication.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
                />
                <FormField
                control={form.control}
                name="studioCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-landing-blue font-medium">
                      {isChamberMode ? "Group Code" : "Studio Code"}
                    </FormLabel>
                    <FormControl>
                      <Input placeholder="12345" disabled={loading} {...field} className="border-landing-blue/20 focus:border-landing-blue" />
                    </FormControl>
                    <FormDescription className="text-landing-blue/60">
                      The 5 character code sent to you by your {isChamberMode ? "group leader" : "teacher"}.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
                />
              <Button className="w-full min-h-[40px] bg-landing-blue text-white hover:bg-landing-blue-hover" type="submit" disabled={loading}>
                {loading ? <LoadingSpinner size="sm" /> : (isChamberMode ? "Join Group" : "Enroll")}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  )
}
