/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bhqpGuFxb21
 */
import { Card, CardContent, CardTitle } from "src/components/ui/card"

import Link from "next/link"
import StudioCard from "./StudioCard"
import { type User } from "@supabase/supabase-js"
import { type StudioWithStudents } from "@/app/(protected)/studios/page"


type Props = {
  studios: StudioWithStudents[],
  user: User
}

export function TeacherDashboard(props: Props) {
  const { user, studios } = props
  const isPaid = true
  return (
    <div className="flex flex-col w-full">
      <main className="container mx-auto px-4 py-16">
        <div className="flex flex-row justify-between items-center mb-12">
          <h1 className="text-4xl font-bold text-landing-blue">
            Welcome{(user.user_metadata.first_name) ? ` ${user.user_metadata.first_name}!` : ""}
          </h1>
          <p className="text-landing-blue/70 text-right">{studios.length} / {isPaid ? 50 : 1} Studios Created</p>
        </div>
        
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
          <Card className="bg-landing-blue text-white flex items-center justify-center w-full h-[20vh] hover:bg-landing-blue-hover transition-colors cursor-pointer">
            <Link className="w-full h-full flex items-center justify-center" href="/studios/new">
              <CardContent className="flex items-center justify-center p-0">
                <PlusIcon className="w-6 h-6 mx-2" />
                <CardTitle className="text-center text-lg">Create New Studio</CardTitle>
              </CardContent>
            </Link>
          </Card>
          {studios.map((studio) => (
            <StudioCard key={studio.code} studio={studio} />
          ))}
        </div>
      </main>
    </div>
  )
}


function PlusIcon(props: { className?: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}